add,delete,update packages

diff --git a/net/wsdd2/files/wsdd2.init b/net/wsdd2/files/wsdd2.init
--- a/net/wsdd2/files/wsdd2.init
+++ b/net/wsdd2/files/wsdd2.init
@@ -16,21 +16,21 @@ start_service() {
 	# needs long delay, otherwise service may not register correctly on stratup/reboot (not sure what the issues is?)
 	sleep 5
 
-	if [ -e /etc/ksmbd/smb.conf ] && [ -e /etc/init.d/ksmbd ] && /etc/init.d/ksmbd running; then
+	if [ -e /etc/ksmbd/smb.conf ] && [ -e /etc/init.d/ksmbd ] ; then
 		SMB_CONF="/etc/ksmbd/smb.conf"
 	fi
 
 	[ -e /etc/samba/smb.conf ] && {
-		if [ -e /etc/init.d/samba4 ] && /etc/init.d/samba4 running; then
+		if [ -e /etc/init.d/samba4 ] ; then
 			SMB_CONF="/etc/samba/smb.conf"
-		elif [ -e /etc/init.d/samba ] && /etc/init.d/samba running; then
+		elif [ -e /etc/init.d/samba ] ; then
 			SMB_CONF="/etc/samba/smb.conf"
 		fi
 	}
 
 	[ -z "$SMB_CONF" ] && {
-		logger -p daemon.info -t 'wsdd2' "samba36/4 or ksmbd is not running"
-		return
+		logger -p daemon.error -t 'wsdd2' "samba36/4 or ksmbd is not running, can't start wsdd2!"
+		exit 1
 	}
 	
 	# cleanup comments
@@ -59,12 +59,12 @@ start_service() {
 	local board_sku
 
 	[ -e /tmp/sysinfo/board_name ] && {
-		board_vendor="$(awk -F',' '{print $1}' /tmp/sysinfo/board_name | tr ' ' '_' | tr ',' '-' | tr -d ' \n')"
-		board_sku="$(awk -F',' '{print $2}' /tmp/sysinfo/board_name | tr ' ' '_' | tr ',' '-' |  tr -d ' \n')"
+		board_vendor="$(awk -F',' '{print $1}' /tmp/sysinfo/board_name | tr ' ' '_' | tr -d ' \n')"
+		board_sku="$(awk -F',' '{print $2}' /tmp/sysinfo/board_name | tr ' ' '_' | tr -d ' \n')"
 	}
 
 	[ -e /tmp/sysinfo/model ] && {
-		board_model="$(awk -F':' '{print $1}' /tmp/sysinfo/model | tr ' ' '_' | tr ',' '-' |  tr -d ' \n')"
+		board_model="$(awk -F':' '{print $1}' /tmp/sysinfo/model | tr ' ' '_' | tr -d ' \n')"
 	}
 
 	[ -n "$board_vendor" ] && [ -n "$board_model" ] && {
diff --git a/utils/cache-domains/files/cache-domains b/utils/cache-domains/files/cache-domains
--- a/utils/cache-domains/files/cache-domains
+++ b/utils/cache-domains/files/cache-domains
@@ -6,40 +6,21 @@ set -e
 
 CACHE_DOMAINS_SRC="https://api.github.com/repos/uklans/cache-domains/tarball/master"
 CACHE_DOMAINS_DIR="/var/cache-domains"
-CACHE_DOMAINS_CONF_FILE="${CACHE_DOMAINS_DIR}/lancache.conf"
+CACHE_DOMAINS_HOSTS_DIR="${CACHE_DOMAINS_DIR}/scripts/output/dnsmasq/hosts"
 CONFIG_FILE="/etc/cache-domains.json"
 
-dnsmasq_conf() {
-	local I=0
-	local DNSMASQ_CONF_DIR
-	local DNSMASQ_CONF_FILE
+uci_changes() {
+	local PACKAGE="$1"
+	local STATE="$2"
 
-	while uci_get "dhcp" "@dnsmasq[${I}]" > /dev/null; do
-		DNSMASQ_CONF_DIR="$(uci_get "dhcp" "@dnsmasq[${I}]" "confdir" "/tmp/dnsmasq.d" || :)"
-		DNSMASQ_CONF_FILE="${DNSMASQ_CONF_DIR}/$(basename "${CACHE_DOMAINS_CONF_FILE}")"
-
-		case ${1} in
-			add)
-				ln -sf "${CACHE_DOMAINS_CONF_FILE}" "${DNSMASQ_CONF_FILE}"
-				;;
-			remove)
-				rm -f "${DNSMASQ_CONF_FILE}"
-				;;
-			*)
-				echo "ERROR: Invalid action '${1}' for dnsmasq_conf()"
-				return 1
-				;;
-		esac
-
-		I=$((${I} + 1))
-	done
-
-	/etc/init.d/dnsmasq "restart"
+	CHANGES=$(/sbin/uci ${UCI_CONFIG_DIR:+-c ${UCI_CONFIG_DIR}} ${STATE:+-P ${STATE}} -q changes "${PACKAGE}" | wc -l)
+	return "${CHANGES}"
 }
 
 configure() {
 	local INITIAL_DIR
-	local SOURCE_DIR
+	local I=0
+
 	mkdir -p "${CACHE_DOMAINS_DIR}"
 	rm -fr "${CACHE_DOMAINS_DIR:?}/"*
 
@@ -48,26 +29,54 @@ configure() {
 		echo "ERROR: Could not retrieve ${CACHE_DOMAINS_SRC}"
 		exit 1
 	fi
-	SOURCE_DIR="${CACHE_DOMAINS_DIR}/$(ls "${CACHE_DOMAINS_DIR}")"
+
+	# move files out of versioned directory
+	mv "${CACHE_DOMAINS_DIR}/"*"/"* "${CACHE_DOMAINS_DIR}/"
 
 	if [ ! -f "${CONFIG_FILE}" ]; then
-		cp "${SOURCE_DIR}/scripts/config.example.json" "${CONFIG_FILE}"
+		cp "${CACHE_DOMAINS_DIR}/scripts/config.example.json" "${CONFIG_FILE}"
 		echo "Using example config file ${CONFIG_FILE}"
 	fi
 
 	INITIAL_DIR="$(pwd)"
-	cd "${SOURCE_DIR}/scripts/"
+	cd "${CACHE_DOMAINS_DIR}/scripts/"
 	cp "${CONFIG_FILE}" "config.json"
 	./create-dnsmasq.sh > /dev/null
-	cat "./output/dnsmasq/"*".conf" > "${CACHE_DOMAINS_CONF_FILE}"
+	rm "config.json" "${CACHE_DOMAINS_HOSTS_DIR}/../lancache.conf"
 	cd "${INITIAL_DIR}"
-	rm -fr "${SOURCE_DIR}"
 
-	dnsmasq_conf add
+	while uci_get "dhcp" "@dnsmasq[${I}]" > /dev/null; do
+		if uci_changes "dhcp"; then
+			uci_remove_list	"dhcp" "@dnsmasq[${I}]" "addnhosts" "${CACHE_DOMAINS_HOSTS_DIR}"
+			uci_add_list	"dhcp" "@dnsmasq[${I}]" "addnhosts" "${CACHE_DOMAINS_HOSTS_DIR}"
+			uci_commit		"dhcp"
+		else
+			echo "ERROR: Unexpected changes in the dhcp configuration, commit changes and try again"
+			exit 1
+		fi
+
+		I=$((${I} + 1))
+	done
+
+	/etc/init.d/dnsmasq "restart"
 }
 
 cleanup() {
-	dnsmasq_conf remove
+	local I=0
+
+	while uci_get "dhcp" "@dnsmasq[${I}]" > /dev/null; do
+		if uci_changes "dhcp"; then
+			uci_remove_list	"dhcp" "@dnsmasq[${I}]" "addnhosts" "${CACHE_DOMAINS_HOSTS_DIR}"
+			uci_commit		"dhcp"
+		else
+			echo "ERROR: Unexpected changes in the dhcp configuration, commit changes and try again"
+			exit 1
+		fi
+
+		I=$((${I} + 1))
+	done
+
+	/etc/init.d/dnsmasq "restart"
 }
 
 case ${1} in
